version: '3.3'

services:
  nginx:
    image: nginx
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  web:
    build: .
    ports:
      - 3000:3000
